version: "3.1"
services:

  mysql:
    image: mysql:5.7
    container_name: marvel-app-mysql
    working_dir: /application
    volumes:
      - ./marvel-app-backend:/application
      - ./marvel-app-backend/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: "marvel-root"
      MYSQL_DATABASE: "marvel"
      MYSQL_USER: "marvel-admin"
      MYSQL_PASSWORD: "marvel-password"
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"

  webserver:
    image: nginx:alpine
    container_name: marvel-app-webserver
    working_dir: /application
    volumes:
      - ./marvel-app-backend:/application
      - ./marvel-app-backend/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"

  php-fpm:
    build: 
      context: ./marvel-app-backend
      dockerfile: Dockerfile
    container_name: marvel-app-php-fpm
    working_dir: /application
    volumes:
      - ./marvel-app-backend:/application
      - ./marvel-app-backend/docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

  node:
    container_name: marvel-app-client
    build:
      context: ./marvel-app-frontend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
